apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-info-deployment
  labels:
    app: devops-info
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: devops-info
  template:
    metadata:
      labels:
        app: devops-info
    spec:
      containers:
        - name: devops-info
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5000

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 3

      restartPolicy: Always
