apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-info-deployment
  labels:
    app: devops-info
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: devops-info
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app: devops-info
    spec:
      containers:
        - name: devops-info
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5000
              name: http

          envFrom:
            - configMapRef:
                name: devops-info-env

          volumeMounts:
            - name: app-config
              mountPath: /config
              readOnly: true
            - name: app-data
              mountPath: /data
            - name: app-secret
              mountPath: "/etc/app-secret"
              readOnly: true

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 3

      volumes:
        - name: app-config
          configMap:
            name: devops-info-config
        - name: app-data
          persistentVolumeClaim:
            claimName: devops-info-data
        - name: app-secret
          secret:
            secretName: {{ .Release.Name }}-secret

      restartPolicy: Always
